### PR TITLE
added destroy method

### PR DESCRIPTION
**Pull request by tobaiasjl**

### CODE REVIEW

**Comment by mhuggins** [comment]
This looks similar to what #39 is trying to achieve.  However, while I like the idea, I'd rather support jQuery's standard method of implementing plugin-specific functions, e.g.: `$(element).countTo('stop')`.  I made a pretty significant change under the [rewrite branch](https://github.com/mhuggins/jquery-countTo/tree/rewrite#functions), but I need to address one example that no longer works there before I think it is ready.

**Comment by tobaiasjl** [comment]
okey nice the file in the rewrite branch looks create and very clean! :+1:

**Comment by mhuggins** [comment]
I've updated master and bumped the version to 1.1.0. Let me know if you run into any problems!

**Comment by tobaiasjl** [comment]
i've just added the new script. but i'm afraid i get an error on line https://github.com/mhuggins/jquery-countTo/blob/master/jquery.countTo.js#L112

the error message is stop doesnt exist in stop...

**Comment by mhuggins** [comment]
Mind sharing what your JS and relevant markups looks like?

**Comment by tobaiasjl** [comment]
im just preparing the deployment

**Comment by mhuggins** [comment]
I've got a training session all day, but I'll try to take a look tonight.  Otherwise, let me know if you see what's going on in the interim!

**Pull request closed without merging**
