### PR TITLE
Added easing functions

### PR DESCRIPTION
**Pull request by steve-king**
Hi mhuggins,

I really like your plugin, nice and simple and does what I needed it to. A colleague of mine wondered if I could add easing to the counting so I forked your plugin and added the necessary code today.

You can see it in action on the "Earth's Gravity" and "Earth's Radius" examples.

Unfortunately I haven't had time to update the readme.

If you like this please feel free to merge in these changes. Enjoy!

Steve

### CODE REVIEW

**Comment by ducdigital** [comment]
Can you merge this?

**Comment by mhuggins** [comment]
@ducdigital I'm interested in the question I asked @steve-king before merging.

**Comment by VoidZA** [comment]
Thank you steve-king

**Review by nkals722 — APPROVED** [review]

**Comment by trijste** [comment]
@mhuggins Looks like the default easing is set to linear in the updated code. Linear would be the same as no easing (old functionality). Documentation needs updating though as it's not clear to me what the different cases do.

**Comment by mhuggins** [comment]
Closing due to lack of response.

**Pull request closed without merging**
